config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show, :edit, :update]

  root 'static_pages#home'
  get '/auth/facebook/callback' => 'session#create'

  controller :session do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :meetup
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :venue
  has_many :meetups
  has_and_belongs_to_many :users
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :event
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_and_belongs_to_many :meetups
  has_and_belongs_to_many :events
  has_many :comments
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :events
  has_many :users, through: :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :verify_user_is_authenticated
  helper_method :current_user

  private
  def verify_user_is_authenticated
    redirect_to '/' unless user_is_authenticated
  end

  def user_is_authenticated
    !!current_user
  end

  def current_user
    User.find_by(id:session[:user_id])
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :verify_user_is_authenticated, only: [:new,:create]
  def new
   @user = User.new
 end

 def create
   if auth
     sign_in_with_auth(auth)
   else
     sign_in_with_password
   end
  end


 def destroy
   session.delete :user_id
   redirect_to root_path
 end

private

   def auth
    request.env['omniauth.auth']
  end

  def sign_in_with_auth(auth)
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
      u.image = auth['info']['image']
      u.password = 'asdfgasgadfgsdfhscnbq345'
    end
    session[:user_id] = @user.id
    redirect_to edit_user_path(@user)
  end

  def sign_in_with_password
    @user = User.find_by(email: params[:user][:email])
    if @user
      session[:user_id] = @user.id
      redirect_to edit_user_path(@user)
    else
      render 'new'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :verify_user_is_authenticated, only: [:home]
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_user_is_authenticated, only: [:new,:create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by(id: session[:user_id])
  end

  def show
  end

  private
    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :password,
        :about,
        )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <title>EventHub</title>
  </head>
  <body class="bg">

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '{your-app-id}',
      cookie     : true,
      xfbml      : true,
      version    : '{latest-api-version}'
    });

    FB.AppEvents.logPageView();

  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">EventHub</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%if !current_user%>
              <a class="navbar-brand" href="<%= new_user_path %>"/>Sign Up</a>
              <a class="navbar-brand" href="<%= login_path %>"/>Log In</a>
            <%end%>
            <%if current_user%>
              <%= button_to 'Logout', logout_path, :method => :delete, class: "btn btn-outline-warning btn-sm"%>

            <%end%>
          </div>
        </div>
      </nav>
    </div>


    <!-- content -->
    <div class="container main-box"  role="main">
        <%= yield %>
    </div>
  </body>
</html>

app/views/session/new.html.erb
<div class="row">
  <div class="col-sm-6 mx-auto pt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="text-center pb-3">Welcome Back!</h5>
        <%= link_to('Log in with Facebook!', '/auth/facebook', class:"btn btn-primary btn-block mb-4")%>
        <p class="text-center">or</p>
        <hr>
        <h5 class="card-title pb-3">Log-in To Your Account</h5>
        <%= form_for @user do |f| %>

        <div class="form-group">
        <%= f.label "Email" %>
        <br>
        <%= f.email_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password, "Password" %>
          <br>
          <%= f.password_field :password, class: "form-control" %>
        </div>

          <div class="actions">
            <br/>
            <%= f.submit "Log In", class: "btn btn-primary" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>

app/views/users/_edit_form.html.erb
<%= form_for @user do |f| %>

    <div class="form-group">
    <%= f.label "Name" %>
    <br>
    <%= f.text_field :name, class: "form-control", :placeholder => (@user.name || 'What is your name?') %>
  </div>

  <div class="form-group">
    <%= f.label "About Me" %>
    <br>
    <%= f.text_area :about, class: "form-control", :placeholder => (@user.about || 'Tell us a little about yourself....') %>
  </div>

  <div class="actions">
    <br/>
    <%= f.submit "Update profile", class: "btn btn-primary" %>
  </div>


<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<div class="form-group">
<%= f.label "Email" %>
<br>
<%= f.email_field :email, class: "form-control", :placeholder => (@user.errors.full_messages_for(:email).first) %>
</div>

<div class="form-group">
  <%= f.label :password, "Choose Password" %>
  <br>
  <%= f.password_field :password, class: "form-control" , :placeholder => (@user.errors.full_messages_for(:password).first) %>
</div>

  <div class="form-group">
    <%= f.label "Confirm Password" %>
    <br>
    <%= f.password_field :password_confirmation, class: "form-control", :placeholder => (@user.errors.full_messages_for(:password_confirmation).first)%>
  </div>

  <hr/>
    <div class="form-group">
    <%= f.label "Name" %>
    <br>
    <%= f.text_field :name, class: "form-control", :placeholder => (@user.errors.full_messages_for(:first_name).first) %>
  </div>

  <div class="form-group">
    <%= f.label "About Me" %>
    <br>
    <%= f.text_area :about, class: "form-control" %>
  </div>

  <div class="actions">
    <br/>
    <%= f.submit "Open Account", class: "btn btn-primary" %>
  </div>


<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-6 mx-auto pt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title pb-3 text-center">Edit Your Profile</h5>
          <%= render 'edit_form' %>
        </div>
      </div>
    </div>
  </div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-6 mx-auto pt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title pb-3 text-center">Start The Party Today</h5>
        <%= link_to('Log in with Facebook!', '/auth/facebook', class:"btn btn-primary btn-block mb-4")%>

        <p class="text-center">or</p>
        <h5 class="card-title pb-3 text-center">Sign-up To EventHub</h5>
        <%= render 'form' %>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<%= button_to 'Logout', logout_path, :method => :delete %>